In [1]:
import os
os.environ["HF_HOME"] = "/scratch/heli"
os.environ["HF_DATASETS_CACHE"] = "/scratch/heli"

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM

In [3]:
model_name = "meta-llama/Llama-3.2-1B-Instruct"

In [4]:
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto")

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [5]:
model.save_pretrained('/scratch/heli/models_from_hf/llama_1b_inst')

In [6]:
tok = AutoTokenizer.from_pretrained(model_name)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

In [7]:
tok.save_pretrained('/scratch/heli/models_from_hf/llama_1b_inst/')

('/scratch/heli/models_from_hf/llama_1b_inst/tokenizer_config.json',
 '/scratch/heli/models_from_hf/llama_1b_inst/special_tokens_map.json',
 '/scratch/heli/models_from_hf/llama_1b_inst/tokenizer.json')

In [18]:
import pandas as pd
from datasets import load_dataset, load_from_disk

In [39]:
ds = load_from_disk('./ai4bharat/IN22-Conv/')

In [40]:
ds = ds['test']
ds

Dataset({
    features: ['doc_id', 'sent_id', 'topic', 'domain', 'prompt', 'scenario', 'speaker', 'turn', 'asm_Beng', 'ben_Beng', 'brx_Deva', 'doi_Deva', 'eng_Latn', 'gom_Deva', 'guj_Gujr', 'hin_Deva', 'kan_Knda', 'kas_Arab', 'mai_Deva', 'mal_Mlym', 'mar_Deva', 'mni_Mtei', 'npi_Deva', 'ory_Orya', 'pan_Guru', 'san_Deva', 'sat_Olck', 'snd_Deva', 'tam_Taml', 'tel_Telu', 'urd_Arab'],
    num_rows: 1503
})

In [36]:
ds['eng_Latn'][0]

"Mom, let's go for a movie tomorrow."

In [37]:
ds['guj_Gujr'][0]

'મમ્મી, ચાલો આપણે આવતીકાલે ફિલ્મ જોવા જઇએ.'

In [1]:
from datasets import load_from_disk

In [42]:
ds_conv = load_from_disk('../Layerwise/Data/ai4bharat/IN22-Conv/')['test']
ds_gen = load_from_disk('../Layerwise/Data/ai4bharat/IN22-Gen/')['test']
ds_flores = load_from_disk('../Layerwise/Data/openlanguagedata/flores_plus/',  "default")

In [43]:
ds_gen, ds_conv

(Dataset({
     features: ['context', 'source', 'url', 'domain', 'num_words', 'bucket', 'asm_Beng', 'ben_Beng', 'brx_Deva', 'doi_Deva', 'eng_Latn', 'gom_Deva', 'guj_Gujr', 'hin_Deva', 'kan_Knda', 'kas_Arab', 'mai_Deva', 'mal_Mlym', 'mar_Deva', 'mni_Mtei', 'npi_Deva', 'ory_Orya', 'pan_Guru', 'san_Deva', 'sat_Olck', 'snd_Deva', 'tam_Taml', 'tel_Telu', 'urd_Arab'],
     num_rows: 1024
 }),
 Dataset({
     features: ['doc_id', 'sent_id', 'topic', 'domain', 'prompt', 'scenario', 'speaker', 'turn', 'asm_Beng', 'ben_Beng', 'brx_Deva', 'doi_Deva', 'eng_Latn', 'gom_Deva', 'guj_Gujr', 'hin_Deva', 'kan_Knda', 'kas_Arab', 'mai_Deva', 'mal_Mlym', 'mar_Deva', 'mni_Mtei', 'npi_Deva', 'ory_Orya', 'pan_Guru', 'san_Deva', 'sat_Olck', 'snd_Deva', 'tam_Taml', 'tel_Telu', 'urd_Arab'],
     num_rows: 1503
 }))

In [44]:
ds_flores

DatasetDict({
    dev: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 223328
    })
    devtest: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 220616
    })
})

In [45]:
ds = ds_flores
tgt_langs = ds["devtest"]["iso_639_3"]
src_langs = ds["devtest"]["iso_639_3"]

eng_ds = ds['devtest'].filter(lambda x: x['iso_639_3']=='eng')
hin_ds = ds['devtest'].filter(lambda x: x['iso_639_3']=='hin')


eng_hin = []
hin_eng = []

eng_src = []
hin_src = []

# prompt = """Translate the following text from {SOURCE_LANGUAGE} to {TARGET_LANGUAGE}.
# Ensure the translation is accurate, fluent, and faithful to the original meaning.
# Do not add, remove, or change any information.

# Text:
# {SOURCE_TEXT}"""

prompt = """Translate following {SOURCE_LANGUAGE} dialogue to {TARGET_LANGUAGE}.\nSource Sentence:\n{SOURCE_TEXT}\nTarget:\n{TARGET_TEXT}"""

eng_src.extend([*eng_ds['text']])#, *in22_gen['test']['eng_Latn'], *in22_conv['test']['eng_Latn']])
hin_src.extend([*hin_ds['text']])#, *in22_gen['test']['hin_Deva'], *in22_conv['test']['hin_Deva']])

eng_hin.extend([prompt.format(SOURCE_LANGUAGE="English", TARGET_LANGUAGE="Hindi", SOURCE_TEXT=s.strip(), TARGET_TEXT=t.strip()) for s,t in zip(eng_ds['text'], hin_ds['text'])])
eng_hin.extend([prompt.format(SOURCE_LANGUAGE="English", TARGET_LANGUAGE="Hindi", SOURCE_TEXT=s.strip(), TARGET_TEXT=t.strip()) for s,t in zip(ds_gen['eng_Latn'], ds_gen['hin_Deva'])])
eng_hin.extend([prompt.format(SOURCE_LANGUAGE="English", TARGET_LANGUAGE="Hindi", SOURCE_TEXT=s.strip(), TARGET_TEXT=t.strip()) for s,t in zip(ds_conv['eng_Latn'], ds_conv['hin_Deva'])])

# hin_eng.extend([prompt.format(SOURCE_LANGUAGE="Hindi", TARGET_LANGUAGE="English", SOURCE_TEXT=s.strip()) for s in hin_ds['text']])

Filter:   0%|          | 0/220616 [00:00<?, ? examples/s]

Filter:   0%|          | 0/220616 [00:00<?, ? examples/s]

In [51]:
print(eng_hin[100])

Translate following English dialogue to Hindi.
Source Sentence:
In one year's time, an infected person may infect 10 to 15 close contacts.
Target:
एक साल के दौरान, एक संक्रमित व्यक्ति 10 से 15 करीबी संपर्कों को संक्रमित कर सकता है.

In [47]:
len(eng_ds)

1012

In [48]:
len(hin_ds)

1012

In [49]:
len(eng_hin)

3539

In [50]:
ds_flores['devtest'][0]

{'id': 0,
 'iso_639_3': 'ace',
 'iso_15924': 'Arab',
 'glottocode': 'achi1257',
 'variant': '',
 'text': '"کامو جينو نا تيكويه عمو ٤ بولن ڽڠ هانا ديابيتيس ڽڠ اوايجيه ساکيت ديابيتيس،" غتامه لى غوبڽن.',
 'url': 'https://en.wikinews.org/wiki/Toronto_team-led_research_on_Type_1_Diabetes_%27groundbreaking%27',
 'domain': 'wikinews',
 'topic': 'disease, research, canada',
 'has_image': 'no',
 'has_hyperlink': 'yes',
 'last_updated': '1.0',
 'split': 'devtest'}

In [53]:
import pandas as pd

In [54]:
df = pd.DataFrame({
    "prompt": eng_hin
})

In [56]:
df.to_csv('./train_dataset.tsv', sep='\t')

In [57]:
ds = load_from_disk('../Layerwise/Data/Opus_Test_Data_en_hi/')

In [61]:
ds = ds.select(range(100))

In [67]:
eng_hin = []
hin_eng = []

prompt = """Translate following {SOURCE_LANGUAGE} dialogue to {TARGET_LANGUAGE}.\nSource Sentence:\n{SOURCE_TEXT}\nTarget:\n{TARGET_TEXT}"""

eng_hin.extend([prompt.format(SOURCE_LANGUAGE="English", TARGET_LANGUAGE="Hindi", SOURCE_TEXT=s.strip(), TARGET_TEXT=t.strip()) for s,t in zip(ds['source'], ds['target'])])

In [70]:
print(eng_hin[0])

Translate following English dialogue to Hindi.
Source Sentence:
Give shots of injections or pills, but he must be alright soon.
Target:
सुई लगाओ या गोली खिलाओ लेकिन इसे जल्दी से ठीक करो.

In [71]:
df = pd.DataFrame({
    "prompt": eng_hin
})

df.to_csv('./valid_dataset.tsv', sep='\t')

In [ ]:
CUDA_VISIBLE_DEVICES=1 python3 llama.py /scratch/heli/models_from_hf/llama_1b_inst c4 --seed 42 --sparsity 0.5 --save /scratch/heli/llama_3B_INST_sparseGPT_pruned_structured_50_4_8 --prunen 4 --prunem 8

In [72]:
"""llama_3B_INST_sparseGPT_pruned_structured_25_1_4
llama_3B_INST_sparseGPT_pruned_structured_25_2_8
llama_3B_INST_sparseGPT_pruned_structured_50_4_8
llama_3B_INST_sparseGPT_pruned_unstructured_25
llama_3B_INST_sparseGPT_pruned_unstructured_75""".split("\n")

['llama_3B_INST_sparseGPT_pruned_structured_25_1_4',
 'llama_3B_INST_sparseGPT_pruned_structured_25_2_8',
 'llama_3B_INST_sparseGPT_pruned_structured_50_4_8',
 'llama_3B_INST_sparseGPT_pruned_unstructured_25',
 'llama_3B_INST_sparseGPT_pruned_unstructured_75']

In [1]:
from huggingface_hub import snapshot_download

In [2]:
snapshot_download(
    repo_id="Yuvrajsinh0409/Llama_1B_inst_in22_flores_ft",
    repo_type="model",
    cache_dir="/scratch/heli/",
    local_dir="/scratch/heli/"
)

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 41 files:   0%|          | 0/41 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

'/scratch/heli'

In [ ]:
/scratch/heli/Llama_FT/merged-checkpoint-280/
/home2/abhinav.pm/yuvraj/Pruning/Layerwise/Data/Opus_Test_Data_en_hi/
'./Inference/Inference_vllm_Llama_3.2_1B_Base.tsv'

python3 llama.py Llama_FT/merged-checkpoint-280/ c4 --seed 42 --sparsity 0.25 --prunen 1 --prunem 4 --save ./llama_1B_INST_FT_sparseGPT_pruned_structured_25_1_4

In [45]:
import random
from tqdm.auto import tqdm
def get_c4(nsamples, seed, seqlen, model, tokenizer):
    traindata = load_dataset(
       "csv",
    data_files='/home/vish/yuvraj/Layerwise/Data/train_dataset.tsv',
    delimiter="\t",
    split="train"
    )
    valdata = load_dataset(
        "csv",
    data_files='/home/vish/yuvraj/Layerwise/Data/valid_dataset.tsv',
    delimiter="\t",
    split="train"
    )

    random.seed(seed)
    trainloader = []
    for _ in tqdm(range(nsamples)):
        while True:
            i = random.randint(0, len(traindata) - 1)
            trainenc = tokenizer(traindata[i]['prompt'], return_tensors='pt')
            print(trainenc.input_ids.shape[1], seqlen)
            if trainenc.input_ids.shape[1] > seqlen:
                break
        i = random.randint(0, trainenc.input_ids.shape[1] - seqlen - 1)
        j = i + seqlen
        inp = trainenc.input_ids[:, i:j]
        tar = inp.clone()
        tar[:, :-1] = -100
        trainloader.append((inp, tar))

    valenc = tokenizer(' '.join(valdata[:1100]['prompt']), return_tensors='pt')
    valenc = valenc.input_ids[:, :(256 * seqlen)]

    class TokenizerWrapper:
        def __init__(self, input_ids):
            self.input_ids = input_ids
    valenc = TokenizerWrapper(valenc)

    return trainloader, valenc


def get_wikitext2(nsamples, seed, seqlen, model, tokenizer):
    
    traindata = load_dataset(
       "csv",
    data_files='/home/vish/yuvraj/Layerwise/Data/train_dataset.tsv',
    delimiter="\t",
    split="train"
    )
    testdata = load_dataset(
        "csv",
    data_files='/home/vish/yuvraj/Layerwise/Data/valid_dataset.tsv',
    delimiter="\t",
    split="train"
    )

    trainenc = tokenizer(" ".join(traindata['prompt']), return_tensors='pt')
    testenc = tokenizer("\n\n".join(testdata['prompt']), return_tensors='pt')

    random.seed(seed)
    trainloader = []
    for _ in range(nsamples):
        i = random.randint(0, trainenc.input_ids.shape[1] - seqlen - 1)
        j = i + seqlen
        inp = trainenc.input_ids[:, i:j]
        tar = inp.clone()
        tar[:, :-1] = -100
        trainloader.append((inp, tar))
    return trainloader, testenc

In [17]:
from datasets import load_from_disk, load_dataset
from transformers import AutoTokenizer

In [35]:
def get_tokenizer(model):
    if "llama" in model.lower():
        tokenizer = AutoTokenizer.from_pretrained(model, use_fast=False)
        # fix for transformer 4.28.0.dev0 compatibility
        if tokenizer.bos_token_id != 1 or tokenizer.eos_token_id != 2:
            try:
                tokenizer.bos_token_id = 1
                tokenizer.eos_token_id = 2
            except AttributeError:
                pass
    else:
        tokenizer = AutoTokenizer.from_pretrained(model, use_fast=False)
    return tokenizer

tok = get_tokenizer('./Llama_FT/merged-checkpoint-280/')

In [18]:
tokenizer = AutoTokenizer.from_pretrained('./Llama_FT/merged-checkpoint-280/')

In [11]:
ds = load_dataset("csv",
    data_files='./train_dataset.tsv',
    delimiter="\t",
    split="train")

Generating train split: 0 examples [00:00, ? examples/s]

In [13]:
ds[0]["prompt"]

'Translate following English dialogue to Hindi.\nSource Sentence:\n"We now have 4-month-old mice that are non-diabetic that used to be diabetic," he added.\nTarget:\nउन्होंने कहा “कि अब हमारे पास 4 महीने उम्र वाले चूहे हैं जिन्हें मधुमेह नहीं है जो मधुमेह के रोगी थे। ”'

In [44]:
d = get_c4(nsamples=128, seed=42, seqlen=150, model=None, tokenizer=tok)

  0%|          | 0/128 [00:00<?, ?it/s]

48 150
91 150
122 150
81 150
190 150
119 150
129 150
63 150
124 150
41 150
62 150
57 150
85 150
38 150
110 150
103 150
76 150
132 150
104 150
134 150
34 150
37 150
166 150
62 150
37 150
34 150
33 150
105 150
69 150
79 150
42 150
73 150
41 150
115 150
35 150
54 150
85 150
53 150
101 150
79 150
90 150
111 150
112 150
72 150
92 150
117 150
71 150
103 150
100 150
97 150
41 150
61 150
95 150
260 150
92 150
38 150
239 150
157 150
128 150
41 150
201 150
74 150
45 150
46 150
61 150
103 150
79 150
66 150
91 150
49 150
118 150
32 150
117 150
140 150
41 150
116 150
84 150
103 150
90 150
70 150
22 150
51 150
92 150
108 150
151 150
65 150
37 150
113 150
59 150
35 150
28 150
104 150
59 150
51 150
84 150
72 150
36 150
66 150
107 150
92 150
282 150
93 150
38 150
94 150
71 150
49 150
140 150
36 150
51 150
52 150
75 150
66 150
39 150
143 150
26 150
146 150
137 150
65 150
146 150
108 150
34 150
45 150
190 150
95 150
46 150
116 150
56 150
206 150
197 150
84 150
37 150
41 150
75 150
189 150
168 150
83 150
75 150
130 150
46 150
192 150
35 150
120 150
46 150
131 150
73 150
60 150
103 150
52 150
51 150
83 150
45 150
107 150
83 150
361 150
145 150
74 150
99 150
63 150
58 150
95 150
52 150
35 150
81 150
33 150
48 150
42 150
100 150
48 150
50 150
79 150
91 150
99 150
216 150
185 150
42 150
26 150
358 150
81 150
114 150
39 150
106 150
57 150
130 150
39 150
90 150
39 150
32 150
107 150
73 150
84 150
57 150
71 150
56 150
82 150
49 150
148 150
32 150
117 150
129 150
138 150
148 150
78 150
64 150
28 150
60 150
88 150
128 150
58 150
34 150
128 150
97 150
32 150
62 150
40 150
104 150
60 150
70 150
27 150
96 150
81 150
108 150
103 150
59 150
89 150
142 150
34 150
42 150
94 150
153 150
66 150
25 150
31 150
85 150
69 150
148 150
108 150
56 150
37 150
56 150
242 150
116 150
155 150
72 150
56 150
64 150
149 150
38 150
34 150
125 150
36 150
69 150
61 150
112 150
82 150
50 150
108 150
97 150
126 150
124 150
74 150
130 150
112 150
35 150
131 150
96 150
27 150
164 150
48 150
108 150
56 150
36 150
39 150
123 150
128 150
19 150
209 150
248 150
131 150
65 150
53 150
85 150
124 150
117 150
199 150
29 150
36 150
80 150
44 150
35 150
60 150
122 150
133 150
118 150
32 150
66 150
43 150
45 150
110 150
98 150
82 150
80 150
57 150
399 150
110 150
73 150
96 150
233 150
70 150
259 150
44 150
69 150
50 150
105 150
140 150
49 150
65 150
39 150
106 150
161 150
80 150
121 150
170 150
95 150
99 150
134 150
67 150
119 150
65 150
142 150
177 150
77 150
74 150
146 150
112 150
69 150
32 150
53 150
37 150
52 150
38 150
99 150
46 150
99 150
141 150
76 150
87 150
52 150
21 150
64 150
101 150
112 150
88 150
141 150
147 150
36 150
127 150
59 150
65 150
72 150
104 150
124 150
34 150
127 150
53 150
129 150
79 150
41 150
127 150
41 150
50 150
105 150
108 150
80 150
65 150
72 150
36 150
79 150
151 150
58 150
86 150
67 150
60 150
72 150
54 150
192 150
42 150
55 150
139 150
79 150
59 150
120 150
150 150
56 150
32 150
111 150
234 150
66 150
69 150
79 150
117 150
48 150
51 150
96 150
85 150
69 150
111 150
97 150
177 150
167 150
105 150
72 150
75 150
63 150
242 150
29 150
78 150
70 150
28 150
71 150
70 150
114 150
55 150
75 150
33 150
260 150
169 150
260 150
93 150
42 150
63 150
111 150
46 150
199 150
84 150
38 150
64 150
105 150
39 150
53 150
58 150
228 150
129 150
178 150
94 150
122 150
42 150
117 150
47 150
122 150
100 150
138 150
209 150
129 150
61 150
198 150
71 150
183 150
61 150
63 150
148 150
70 150
37 150
92 150
57 150
103 150
33 150
228 150
54 150
73 150
170 150
72 150
60 150
117 150
59 150
58 150
106 150
163 150
50 150
82 150
57 150
110 150
56 150
66 150
107 150
121 150
65 150
76 150
122 150
148 150
127 150
106 150
44 150
83 150
98 150
150 150
110 150
63 150
175 150
80 150
42 150
39 150
44 150
109 150
100 150
62 150
47 150
34 150
74 150
123 150
109 150
50 150
343 150
132 150
39 150
63 150
66 150
172 150
74 150
86 150
40 150
122 150
142 150
122 150
100 150
66 150
60 150
79 150
84 150
37 150
89 150
264 150
60 150
57 150
106 150
78 150
99 150
114 150
114 150
37 150
59 150
151 150
60 150
183 150
49 150
28 150
88 150
70 150
44 150
43 150
72 150
116 150
51 150
107 150
97 150
68 150
80 150
145 150
61 150
34 150
45 150
107 150
39 150
31 150
72 150
60 150
43 150
74 150
88 150
130 150
68 150
44 150
74 150
41 150
95 150
66 150
41 150
120 150
40 150
224 150
171 150
96 150
106 150
45 150
66 150
97 150
124 150
122 150
206 150
119 150
23 150
51 150
77 150
44 150
117 150
108 150
137 150
42 150
35 150
173 150
153 150
170 150
42 150
48 150
170 150
183 150
39 150
95 150
52 150
114 150
24 150
59 150
53 150
83 150
68 150
112 150
97 150
32 150
55 150
63 150
44 150
79 150
161 150
69 150
299 150
45 150
142 150
108 150
74 150
118 150
66 150
103 150
80 150
42 150
51 150
51 150
241 150
53 150
61 150
77 150
38 150
49 150
243 150
110 150
70 150
117 150
115 150
69 150
146 150
42 150
50 150
32 150
117 150
65 150
97 150
102 150
74 150
28 150
67 150
47 150
76 150
147 150
117 150
109 150
44 150
157 150
134 150
59 150
115 150
70 150
72 150
73 150
65 150
95 150
66 150
74 150
35 150
33 150
31 150
53 150
142 150
69 150
42 150
166 150
56 150
44 150
201 150
101 150
66 150
124 150
38 150
47 150
58 150
27 150
73 150
38 150
121 150
33 150
105 150
83 150
129 150
98 150
48 150
116 150
193 150
181 150
65 150
77 150
130 150
69 150
54 150
159 150
47 150
97 150
76 150
122 150
196 150
32 150
120 150
228 150
127 150
40 150
65 150
92 150
54 150
36 150
37 150
93 150
57 150
98 150
82 150
80 150
185 150
83 150
88 150
32 150
123 150
39 150
33 150
85 150
110 150
38 150
24 150
44 150
106 150
82 150
120 150
110 150
75 150
45 150
85 150
170 150
134 150
270 150
39 150
117 150
92 150
32 150
89 150
42 150
82 150
109 150
39 150
72 150
85 150
181 150
66 150
52 150
49 150
165 150
83 150
90 150
83 150
95 150
147 150
107 150
119 150
44 150
111 150
96 150
133 150
82 150
39 150
119 150
73 150
27 150
31 150
90 150
131 150
27 150
131 150
152 150
75 150
56 150
87 150
143 150
64 150
30 150
72 150
82 150
55 150
66 150
61 150
144 150
124 150
110 150
64 150
129 150
48 150
79 150
79 150
59 150
96 150
69 150
143 150
69 150
132 150
99 150
44 150
108 150
65 150
70 150
140 150
39 150
35 150
112 150
38 150
81 150
73 150
35 150
120 150
127 150
74 150
48 150
72 150
75 150
82 150
23 150
262 150
77 150
96 150
73 150
56 150
75 150
69 150
52 150
62 150
131 150
45 150
79 150
162 150
41 150
62 150
155 150
80 150
147 150
96 150
80 150
168 150
48 150
97 150
57 150
60 150
132 150
37 150
65 150
75 150
76 150
87 150
196 150
22 150
59 150
114 150
40 150
73 150
98 150
82 150
60 150
73 150
32 150
79 150
32 150
54 150
110 150
73 150
114 150
99 150
186 150
223 150
69 150
69 150
121 150
104 150
100 150
101 150
115 150
29 150
62 150
46 150
119 150
67 150
107 150
103 150
35 150
56 150
95 150
96 150
111 150
88 150
91 150
67 150
116 150
132 150
32 150
34 150
249 150
81 150
43 150
70 150
97 150
96 150
43 150
121 150
129 150
106 150
58 150
96 150
75 150
107 150
27 150
34 150
160 150
44 150
95 150
82 150
65 150
140 150
92 150
46 150
62 150
108 150
55 150
60 150
94 150
114 150
46 150
56 150
61 150
146 150
76 150
50 150
127 150
108 150
25 150
185 150
113 150
99 150
192 150
40 150
101 150
146 150
83 150
88 150
55 150
91 150
93 150
91 150
82 150
97 150
73 150
92 150
136 150
47 150
39 150
37 150
59 150
81 150
213 150
157 150
112 150
144 150
96 150
75 150
110 150
107 150
139 150
62 150
72 150
88 150
113 150
66 150
88 150
63 150
62 150
52 150
59 150
45 150
50 150
160 150
60 150
48 150
67 150
118 150
93 150
253 150
100 150
64 150
72 150
45 150
99 150
111 150
62 150
144 150
134 150
63 150
102 150
61 150
60 150
43 150
111 150
81 150
93 150
35 150
71 150
151 150
109 150
131 150
84 150
44 150
126 150
44 150
32 150
43 150
74 150
91 150
33 150
40 150
80 150
89 150
149 150
186 150
172 150
20 150
98 150
48 150
64 150
101 150
67 150
94 150
74 150
108 150
260 150
110 150
60 150
99 150
168 150
90 150
87 150
115 150
97 150
89 150
27 150
68 150
91 150
136 150
79 150
132 150
100 150
64 150
81 150
90 150
62 150
316 150
39 150
95 150
260 150
23 150
32 150
43 150
49 150
44 150
90 150
97 150
129 150
26 150
72 150
57 150
92 150
67 150
50 150
81 150
104 150
88 150
89 150
29 150
60 150
41 150
58 150
57 150
117 150
80 150
100 150
142 150
109 150
30 150
86 150
39 150
106 150
46 150
42 150
38 150
129 150
104 150
101 150
61 150
106 150
237 150
95 150
100 150
72 150
75 150
97 150
65 150
39 150
50 150
59 150
29 150
65 150
42 150
71 150
52 150
89 150
39 150
66 150
49 150
57 150
98 150
343 150
69 150
152 150
112 150
49 150
85 150
51 150
48 150
63 150
117 150
306 150
167 150
158 150
52 150
152 150
168 150
100 150
27 150
127 150
50 150
60 150
63 150
101 150
96 150
112 150
190 150
76 150
111 150
79 150
149 150
31 150
38 150
141 150
119 150
32 150
135 150
111 150
117 150
86 150
52 150
46 150
44 150
65 150
39 150
57 150
210 150
110 150
105 150
113 150
60 150
150 150
71 150
242 150
71 150
157 150
68 150
41 150
72 150
88 150
99 150
105 150
177 150
165 150
198 150
72 150
35 150
115 150
234 150
55 150
33 150
96 150
39 150
88 150
64 150
50 150
81 150
60 150
128 150
27 150
111 150
266 150
189 150
153 150
94 150
91 150
45 150
43 150
147 150
65 150
249 150
41 150
56 150
122 150
53 150
38 150
39 150
122 150
66 150
115 150
81 150
27 150
130 150
44 150
29 150
51 150
40 150
130 150
93 150
90 150
54 150
92 150
148 150
61 150
57 150
67 150
89 150
193 150
172 150
52 150
47 150
66 150
159 150
69 150
64 150
107 150
68 150
103 150
47 150
209 150
32 150
102 150
189 150

In [46]:
d = get_wikitext2(nsamples=128, seed=42, seqlen=2048, model=None, tokenizer=tok)

Token indices sequence length is longer than the specified maximum sequence length for this model (316125 > 131072). Running this sequence through the model will result in indexing errors

In [47]:
d

([(tensor([[100276, 121834, 101782,  ..., 102302, 101795,  35470]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 35470]])),
  (tensor([[ 48909,  35470,  48909,  ..., 100303, 101530, 103673]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 103673]])),
  (tensor([[103396, 116704, 115874,  ..., 100329,  86133, 110016]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 110016]])),
  (tensor([[  1023,   6302,    311,  ...,  35470,  85410, 103552]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 103552]])),
  (tensor([[  7318,   8554,    690,  ..., 100460, 102557,  24810]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 24810]])),
  (tensor([[105135,  45279, 100358,  ...,   1101,   7263,  15256]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 15256]])),
  (tensor([[ 35470,  85410, 100400,  ...,  74958,  10758,    627]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  627]])),
  (tensor([[101201, 100329, 102317,  ..., 100620, 100293,  35470]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 35470]])),
  (tensor([[123418, 106752, 101376,  ..., 102762, 101782,  48909]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 48909]])),
  (tensor([[   627,   3692,  80642,  ..., 100556,  88344, 100271]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100271]])),
  (tensor([[   627,   6531,    512,  ..., 112952, 100549,  85410]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 85410]])),
  (tensor([[100303, 101877, 105603,  ..., 100306,  35470, 103483]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 103483]])),
  (tensor([[ 20397,   1070,   1694,  ..., 100556, 100866, 109222]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 109222]])),
  (tensor([[100750, 100428, 100343,  ..., 100612,  44747, 100293]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100293]])),
  (tensor([[100391, 100349, 123959,  ..., 106432, 101905,  38840]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 38840]])),
  (tensor([[100276, 100482, 126734,  ..., 100271,    220,   1135]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 1135]])),
  (tensor([[ 3692, 80642,   512,  ...,   627,  3692, 80642]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 80642]])),
  (tensor([[ 24810, 101159, 106628,  ..., 101877, 100282,  80338]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 80338]])),
  (tensor([[ 35470, 100293, 100471,  ...,    512,  88344, 100400]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100400]])),
  (tensor([[ 85410, 100436,  38840,  ..., 100391,  48909,  35470]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 35470]])),
  (tensor([[  11,  931,  311,  ...,    0,  279, 5222]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 5222]])),
  (tensor([[  2366,     17,     11,  ...,  45279,  85410, 101207]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 101207]])),
  (tensor([[    13, 108539,     13,  ...,  79468, 108642, 107241]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 107241]])),
  (tensor([[   11,   323,  3885,  ..., 12366,  7327,    11]]),
   tensor([[-100, -100, -100,  ..., -100, -100,   11]])),
  (tensor([[104178, 101376, 103694,  ...,   6498,  21976,    311]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  311]])),
  (tensor([[   969,    396,   3298,  ...,  39951,  48909, 111867]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 111867]])),
  (tensor([[101195,  24810, 101159,  ..., 102223,  69258, 100273]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100273]])),
  (tensor([[100664,  44747,  85410,  ..., 111492,  87262, 101273]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 101273]])),
  (tensor([[   304,    279,   3363,  ...,  35470, 100277, 101282]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 101282]])),
  (tensor([[ 80642,    512,   7955,  ..., 100750,  85410, 101207]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 101207]])),
  (tensor([[100349,  86133, 101166,  ..., 101843,  69258,  35470]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 35470]])),
  (tensor([[100322,  55675, 102927,  ...,  92911,  48909,  24810]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 24810]])),
  (tensor([[101843, 105739,  88344,  ...,  86133, 100358, 100277]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100277]])),
  (tensor([[ 45080,    627,   3692,  ..., 100549, 100782, 100271]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100271]])),
  (tensor([[100625, 100349, 100303,  ...,     11,  84736, 100305]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100305]])),
  (tensor([[100518, 102151,  38840,  ..., 100282,  35470, 100303]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100303]])),
  (tensor([[ 86133, 100515,  80338,  ...,  48909, 102580, 107657]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 107657]])),
  (tensor([[ 21976,    311,  45080,  ...,  44747,  69258, 100750]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100750]])),
  (tensor([[100361,  44747, 116920,  ...,    922,    220,     17]]),
   tensor([[-100, -100, -100,  ..., -100, -100,   17]])),
  (tensor([[ 24810,  85410, 103039,  ...,    627,   6531,    512]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  512]])),
  (tensor([[100411, 100273,  48909,  ...,  24810, 105808,  24810]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 24810]])),
  (tensor([[100331, 101159, 106628,  ...,  44747, 101002, 101344]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 101344]])),
  (tensor([[100280,  92317, 100271,  ...,  45080,    627,   3692]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 3692]])),
  (tensor([[ 88344, 100400, 100291,  ...,   3692,  80642,    512]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  512]])),
  (tensor([[ 92317, 105027,  92911,  ..., 100277, 118758, 100314]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100314]])),
  (tensor([[100276, 100612,  92317,  ..., 104565, 100556, 101495]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 101495]])),
  (tensor([[100404, 100574, 100322,  ...,   1403,   5672,    279]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  279]])),
  (tensor([[   430,   1556,    455,  ..., 101273,  92317, 100799]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100799]])),
  (tensor([[ 80642,    512,  56050,  ..., 100436,  38840,   2768]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 2768]])),
  (tensor([[ 3005,    74, 13279,  ..., 21976,   311, 45080]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 45080]])),
  (tensor([[101391, 100780,  92317,  ...,    584,   3358,    387]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  387]])),
  (tensor([[101276, 101102,  86133,  ..., 101242,  86133, 110019]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 110019]])),
  (tensor([[ 24810, 100277,  24810,  ...,    627,   3692,  80642]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 80642]])),
  (tensor([[  8431,    323,   6411,  ..., 100291, 103008, 100306]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100306]])),
  (tensor([[  4648,    627,   6531,  ..., 101238,  86133, 102122]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 102122]])),
  (tensor([[100511,  61196,  35470,  ...,  35470, 117569, 103887]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 103887]])),
  (tensor([[   512,    791,   1948,  ..., 100349, 102927, 106708]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 106708]])),
  (tensor([[111503, 100580, 100428,  ..., 100622, 100482, 100597]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100597]])),
  (tensor([[   220,    806,    339,  ...,  48909, 108020, 100305]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100305]])),
  (tensor([[ 48909, 103149, 104254,  ...,   8009,    627,   6531]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 6531]])),
  (tensor([[  279,  6412,   315,  ..., 43303,   311, 75277]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 75277]])),
  (tensor([[100460, 100287, 100391,  ..., 106357, 100929, 100280]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100280]])),
  (tensor([[100991, 100799, 100365,  ...,  84736, 106179, 100780]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100780]])),
  (tensor([[ 79468, 100431, 101153,  ..., 100366,  48909,  44747]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 44747]])),
  (tensor([[ 85410, 100400, 100443,  ..., 107778, 101782,  24810]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 24810]])),
  (tensor([[105977, 100273,  44747,  ...,   6498,  21976,    311]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  311]])),
  (tensor([[38840,  2768,  6498,  ...,  3692, 80642,   512]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  512]])),
  (tensor([[112536,  35470, 100866,  ..., 100343, 100515, 100299]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100299]])),
  (tensor([[100358, 101614, 100482,  ...,    430,    814,    649]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  649]])),
  (tensor([[101001, 100664, 100322,  ..., 101376, 101238,  35470]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 35470]])),
  (tensor([[   11,   420, 11847,  ...,  3692, 80642,   512]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  512]])),
  (tensor([[ 84736, 107075, 100625,  ...,   4264,     11,    279]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  279]])),
  (tensor([[ 85410, 100400, 100358,  ...,  24810,  85410, 100266]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100266]])),
  (tensor([[100391,  35470,  85410,  ...,   3552,  25812,    323]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  323]])),
  (tensor([[ 65804, 100580,  85410,  ...,  57770,    380,   5820]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 5820]])),
  (tensor([[102959,  80338, 111166,  ..., 102088, 103022,  61196]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 61196]])),
  (tensor([[ 24810,  85410, 100436,  ..., 100918, 100293, 100666]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100666]])),
  (tensor([[  2768,   6498,  21976,  ..., 100537, 102608, 100781]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100781]])),
  (tensor([[ 24810,  85410, 100266,  ..., 100574, 100393, 102762]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 102762]])),
  (tensor([[100782,  24810, 100293,  ...,  69258, 100750, 100428]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100428]])),
  (tensor([[100306,  48909, 106140,  ..., 127659, 106933, 100515]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100515]])),
  (tensor([[108642,  38840,   2768,  ...,   6531,    512,    679]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  679]])),
  (tensor([[100996,  35470, 120172,  ...,  48909,  24810, 100549]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100549]])),
  (tensor([[101166,  86133, 100358,  ...,    320,  21470,    439]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  439]])),
  (tensor([[ 48909, 100273, 100305,  ..., 100282, 100497, 100291]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100291]])),
  (tensor([[100271, 100697,  44747,  ...,   1727,    278,    483]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  483]])),
  (tensor([[   311,  45080,    627,  ...,    220,   1954, 100291]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100291]])),
  (tensor([[ 38840,   2768,   6498,  ..., 100443, 100731, 100471]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100471]])),
  (tensor([[100406,  69258, 100460,  ..., 100293, 100666, 100311]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100311]])),
  (tensor([[  420,  1917,   627,  ...,  8323, 28904,    11]]),
   tensor([[-100, -100, -100,  ..., -100, -100,   11]])),
  (tensor([[102248, 100411, 110358,  ...,  35470, 100291, 100471]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100471]])),
  (tensor([[101344,     12, 112691,  ..., 126388, 101273, 103608]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 103608]])),
  (tensor([[ 48909, 100511,  48909,  ...,  22643,    627,   6531]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 6531]])),
  (tensor([[100346,  92317, 100271,  ...,  44747,  85410, 103728]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 103728]])),
  (tensor([[  627,  3692, 80642,  ...,   279, 10423,   315]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  315]])),
  (tensor([[    13,  58795,   3629,  ...,  35470,  48909, 106073]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 106073]])),
  (tensor([[118834,  85410, 100400,  ..., 100780, 100428, 101541]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 101541]])),
  (tensor([[ 95048, 102223, 115443,  ..., 122930, 100271, 100366]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100366]])),
  (tensor([[ 24810, 100991,  92317,  ...,   1790,    649,    358]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  358]])),
  (tensor([[   304,   1461,  39007,  ...,  48909, 100273, 102107]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 102107]])),
  (tensor([[  264,  1695,  3463,  ..., 12269,   304, 61507]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 61507]])),
  (tensor([[ 56941,  15323,   1791,  ..., 100518, 100620, 100277]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100277]])),
  (tensor([[ 2768,  6498, 21976,  ..., 45080,   627,  3692]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 3692]])),
  (tensor([[67556,    11,   323,  ...,  7957, 17377,   574]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  574]])),
  (tensor([[ 48909,  55675,  84736,  ...,  44747, 100446, 103133]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 103133]])),
  (tensor([[  555,   279, 16686,  ..., 15489,  1323,  1468]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 1468]])),
  (tensor([[   627,   3692,  80642,  ..., 108590, 106099,  85410]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 85410]])),
  (tensor([[102716,  85410, 100296,  ..., 100781,  38840,   2768]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 2768]])),
  (tensor([[102067, 100329,  55675,  ...,  69258, 100391,  48909]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 48909]])),
  (tensor([[117317, 103396, 100305,  ..., 105222, 102009,  85410]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 85410]])),
  (tensor([[101822, 100460, 100511,  ...,    323,   1077,   4333]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 4333]])),
  (tensor([[  4390,   6531,    512,  ..., 100666, 100311, 100358]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100358]])),
  (tensor([[    11,  23738,    323,  ...,  35470,  85410, 100400]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100400]])),
  (tensor([[100395,  48909,  44747,  ...,    596,   2133,    311]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  311]])),
  (tensor([[108642,  79468, 108642,  ...,  92317, 100271,  92317]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 92317]])),
  (tensor([[   627,   6531,    512,  ...,  44747, 103483,  92317]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 92317]])),
  (tensor([[  2768,   6498,  21976,  ..., 100731, 100311,  48909]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 48909]])),
  (tensor([[107219, 102245,  65804,  ..., 100497, 100482,  85410]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 85410]])),
  (tensor([[100714,  92911,     13,  ..., 100400, 105808,  24810]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 24810]])),
  (tensor([[6531,  512, 5162,  ...,  499,  627, 6531]]),
   tensor([[-100, -100, -100,  ..., -100, -100, 6531]])),
  (tensor([[102534, 100291, 101001,  ...,    311,  45080,    627]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  627]])),
  (tensor([[ 38840,   2768,   6498,  ..., 100305, 100311,  65804]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 65804]])),
  (tensor([[115443,  48909,  44747,  ...,  35470,  48909,  35470]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 35470]])),
  (tensor([[111660, 100580, 100597,  ...,  85410, 100400, 100358]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 100358]])),
  (tensor([[100443, 101166, 111306,  ...,   9675,  56728,  31663]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 31663]])),
  (tensor([[ 21976,    311,  45080,  ..., 102122,  24810, 101159]]),
   tensor([[  -100,   -100,   -100,  ...,   -100,   -100, 101159]])),
  (tensor([[ 2694, 28478,   374,  ...,  2373,    11,   323]]),
   tensor([[-100, -100, -100,  ..., -100, -100,  323]])),
  (tensor([[100444, 113072, 100549,  ..., 100482,  48909,  44747]]),
   tensor([[ -100,  -100,  -100,  ...,  -100,  -100, 44747]]))],
 {'input_ids': tensor([[128000,  28573,   2768,  ...,    320,     67,      8]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1]])})

In [48]:
import shutil

In [49]:
cp = ['/home/vish/tokenizer_config.json', '/home/vish/tokenizer.json', '/home/vish/special_tokens_map.json']

In [56]:
from pathlib import Path
p = Path('./Models/')
models = [i for i in p.glob("llama*")]

In [59]:
for i in models:
    print(i)

Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_75
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_75_6_8
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_50_2_4
Models/llama_3B_INST_sparseGPT_pruned_structured_25_2_8
Models/llama_1B_INST_sparseGPT_pruned_structured_75_3_4
Models/llama_3B_INST_sparseGPT_pruned_structured_25_1_4
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_25_2_8
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_75_3_4
Models/llama_3B_INST_sparseGPT_pruned_structured_75_6_8
Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_50
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_50_2_4
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_50_4_8
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_25_2_8
Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_25
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_25_1_4
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_25
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_75
Models/llama_3B_INST_sparseGPT_pruned_structured_50_4_8
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_75_3_4
Models/llama_3B_INST_sparseGPT_pruned_unstructured_75
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_50_4_8
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_75_6_8
Models/llama_3B_INST_sparseGPT_pruned_unstructured_25
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_50
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_25_1_4

In [58]:
for i in models:
    for j in cp:
        shutil.copy(j, i)

In [61]:
"""Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_75
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_75_6_8
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_50_2_4
Models/llama_3B_INST_sparseGPT_pruned_structured_25_2_8
Models/llama_1B_INST_sparseGPT_pruned_structured_75_3_4
Models/llama_3B_INST_sparseGPT_pruned_structured_25_1_4
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_25_2_8
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_75_3_4
Models/llama_3B_INST_sparseGPT_pruned_structured_75_6_8
Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_50
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_50_2_4
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_50_4_8
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_25_2_8
Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_25
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_25_1_4
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_25
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_75
Models/llama_3B_INST_sparseGPT_pruned_structured_50_4_8
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_75_3_4
Models/llama_3B_INST_sparseGPT_pruned_unstructured_75
Models/llama_1B_INST_FT_sparseGPT_pruned_structured_50_4_8
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_75_6_8
Models/llama_3B_INST_sparseGPT_pruned_unstructured_25
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_50
Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_25_1_4""".split("\n")

['Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_75',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_75_6_8',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_50_2_4',
 'Models/llama_3B_INST_sparseGPT_pruned_structured_25_2_8',
 'Models/llama_1B_INST_sparseGPT_pruned_structured_75_3_4',
 'Models/llama_3B_INST_sparseGPT_pruned_structured_25_1_4',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_25_2_8',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_75_3_4',
 'Models/llama_3B_INST_sparseGPT_pruned_structured_75_6_8',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_50',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_50_2_4',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_50_4_8',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_25_2_8',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_25',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_25_1_4',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_25',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_75',
 'Models/llama_3B_INST_sparseGPT_pruned_structured_50_4_8',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_75_3_4',
 'Models/llama_3B_INST_sparseGPT_pruned_unstructured_75',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_50_4_8',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_75_6_8',
 'Models/llama_3B_INST_sparseGPT_pruned_unstructured_25',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_50',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_25_1_4']

In [62]:
l = ['Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_75',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_75_6_8',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_50_2_4',
 'Models/llama_3B_INST_sparseGPT_pruned_structured_25_2_8',
 'Models/llama_1B_INST_sparseGPT_pruned_structured_75_3_4',
 'Models/llama_3B_INST_sparseGPT_pruned_structured_25_1_4',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_25_2_8',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_75_3_4',
 'Models/llama_3B_INST_sparseGPT_pruned_structured_75_6_8',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_50',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_50_2_4',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_50_4_8',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_25_2_8',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_unstructured_25',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_25_1_4',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_25',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_75',
 'Models/llama_3B_INST_sparseGPT_pruned_structured_50_4_8',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_75_3_4',
 'Models/llama_3B_INST_sparseGPT_pruned_unstructured_75',
 'Models/llama_1B_INST_FT_sparseGPT_pruned_structured_50_4_8',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_75_6_8',
 'Models/llama_3B_INST_sparseGPT_pruned_unstructured_25',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_unstructured_50',
 'Models/llama_1B_INST_trans_prompt_sparseGPT_pruned_structured_25_1_4']

len(l)

25

In [65]:
l = list(Path('./sentence_scores/').glob("*.tsv"))

In [66]:
len(l)

20

In [68]:
import pandas as pd

In [69]:
df = pd.read_csv('./Inference/llama_1B_INST_FT_sparseGPT_pruned_structured_75_3_4.tsv', sep='\t')

In [70]:
df

,Unnamed: 0,Source_Dialogue,Reference,MT
0,0,"Give shots of injections or pills, but he must...",सुई लगाओ या गोली खिलाओ लेकिन इसे जल्दी से ठीक ...,NaN
1,1,"They said, “O Shuaib, we do not understand muc...",और वह लोग कहने लगे ऐ शुएब जो बाते तुम कहते हो ...,.
2,2,- Yeah.,- हाँ.,D.
3,3,If evil befalls him he is perturbed;,"जि उसे तकलीफ़ पहुँचती है तो घबरा उठता है,",NaN
4,4,♪ BE FOREVER BOUND,♪हमेशाके लिएबाध्यहोने,NaN
...,...,...,...,...
1995,1995,Do they not see that Allah enlarges the provis...,क्या उन लोगों ने (इतना भी) ग़ौर नहीं किया कि खु...,NaN
1996,1996,Say: 'Who is the Lord of the heavens and the e...,"कहो, ""आकाशों और धरती का रब कौन है?"" कहो, ""अल्ल...",NaN
1997,1997,-(CELL PHONE RINGING),(सेल फोन बज),D.
1998,1998,"Yeah, smoke it up there, uh, Skippy.","- हाँ, धूंए में उड़ा दो, मेरे शेर.",.
1999,1999,Ctrl-click to open a link,लिंक को खोलने के लिए Ctrl क्लिक करें,D.

In [71]:
df = df.loc[:, ~df.columns.str.contains("^Unnamed")]

In [72]:
df.fillna('-')

,Source_Dialogue,Reference,MT
0,"Give shots of injections or pills, but he must...",सुई लगाओ या गोली खिलाओ लेकिन इसे जल्दी से ठीक ...,-
1,"They said, “O Shuaib, we do not understand muc...",और वह लोग कहने लगे ऐ शुएब जो बाते तुम कहते हो ...,.
2,- Yeah.,- हाँ.,D.
3,If evil befalls him he is perturbed;,"जि उसे तकलीफ़ पहुँचती है तो घबरा उठता है,",-
4,♪ BE FOREVER BOUND,♪हमेशाके लिएबाध्यहोने,-
...,...,...,...
1995,Do they not see that Allah enlarges the provis...,क्या उन लोगों ने (इतना भी) ग़ौर नहीं किया कि खु...,-
1996,Say: 'Who is the Lord of the heavens and the e...,"कहो, ""आकाशों और धरती का रब कौन है?"" कहो, ""अल्ल...",-
1997,-(CELL PHONE RINGING),(सेल फोन बज),D.
1998,"Yeah, smoke it up there, uh, Skippy.","- हाँ, धूंए में उड़ा दो, मेरे शेर.",.
1999,Ctrl-click to open a link,लिंक को खोलने के लिए Ctrl क्लिक करें,D.

In [76]:
p = [i for i in Path('./Inference/').glob("*FT*")]

In [79]:
df = pd.read_csv(p[0])
df

,Unnamed: 0.1,Unnamed: 0,Source_Dialogue,Reference,MT
0,0,0,"Give shots of injections or pills, but he must...",सुई लगाओ या गोली खिलाओ लेकिन इसे जल्दी से ठीक ...,NaN
1,1,1,"They said, “O Shuaib, we do not understand muc...",और वह लोग कहने लगे ऐ शुएब जो बाते तुम कहते हो ...,.
2,2,2,- Yeah.,- हाँ.,D.
3,3,3,If evil befalls him he is perturbed;,"जि उसे तकलीफ़ पहुँचती है तो घबरा उठता है,",NaN
4,4,4,♪ BE FOREVER BOUND,♪हमेशाके लिएबाध्यहोने,NaN
...,...,...,...,...,...
1995,1995,1995,Do they not see that Allah enlarges the provis...,क्या उन लोगों ने (इतना भी) ग़ौर नहीं किया कि खु...,NaN
1996,1996,1996,Say: 'Who is the Lord of the heavens and the e...,"कहो, ""आकाशों और धरती का रब कौन है?"" कहो, ""अल्ल...",NaN
1997,1997,1997,-(CELL PHONE RINGING),(सेल फोन बज),D.
1998,1998,1998,"Yeah, smoke it up there, uh, Skippy.","- हाँ, धूंए में उड़ा दो, मेरे शेर.",.
1999,1999,1999,Ctrl-click to open a link,लिंक को खोलने के लिए Ctrl क्लिक करें,D.

In [80]:
for i in p:
    df = pd.read_csv(i)
    df.fillna('-')
    df.to_csv(i, sep='\t')

In [83]:
d1 = load_from_disk('../Layerwise/Data/ai4bharat/IN22-Conv/')['test']
d2 = load_from_disk('../Layerwise/Data/ai4bharat/IN22-Gen/')['test']
d3 = load_from_disk('../Layerwise/Data/openlanguagedata/flores_plus/')

In [84]:
d1

Dataset({
    features: ['doc_id', 'sent_id', 'topic', 'domain', 'prompt', 'scenario', 'speaker', 'turn', 'asm_Beng', 'ben_Beng', 'brx_Deva', 'doi_Deva', 'eng_Latn', 'gom_Deva', 'guj_Gujr', 'hin_Deva', 'kan_Knda', 'kas_Arab', 'mai_Deva', 'mal_Mlym', 'mar_Deva', 'mni_Mtei', 'npi_Deva', 'ory_Orya', 'pan_Guru', 'san_Deva', 'sat_Olck', 'snd_Deva', 'tam_Taml', 'tel_Telu', 'urd_Arab'],
    num_rows: 1503
})

In [85]:
d2

Dataset({
    features: ['context', 'source', 'url', 'domain', 'num_words', 'bucket', 'asm_Beng', 'ben_Beng', 'brx_Deva', 'doi_Deva', 'eng_Latn', 'gom_Deva', 'guj_Gujr', 'hin_Deva', 'kan_Knda', 'kas_Arab', 'mai_Deva', 'mal_Mlym', 'mar_Deva', 'mni_Mtei', 'npi_Deva', 'ory_Orya', 'pan_Guru', 'san_Deva', 'sat_Olck', 'snd_Deva', 'tam_Taml', 'tel_Telu', 'urd_Arab'],
    num_rows: 1024
})

In [86]:
d3

DatasetDict({
    dev: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 223328
    })
    devtest: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 220616
    })
})

In [87]:
traindata = load_dataset(
       "csv",
    data_files='/home/vish/yuvraj/Layerwise/Data/train_dataset.tsv',
    delimiter="\t",
    split="train"
    )

In [88]:
traindata

Dataset({
    features: ['Unnamed: 0', 'prompt'],
    num_rows: 3539
})

In [89]:
d = load_from_disk('../Layerwise/Data/Opus_Test_Data_en_hi/')

In [90]:
d

Dataset({
    features: ['translation', 'prompt', 'source', 'target'],
    num_rows: 2000
})

In [91]:
df = pd.read_csv('./final_system_scores.tsv', sep='\t')

In [92]:
df

,File_Name,BLEU,chrF++,BERTScore_F1,COMET,COMTAIL
0,llama_1B_INST_FT_sparseGPT_pruned_structured_7...,0.0036,0.1983,0.5841,0.3294,0.0953
1,llama_1B_INST_FT_sparseGPT_pruned_structured_5...,0.3957,1.0041,0.6440,0.3787,0.2173
2,llama_1B_INST_FT_sparseGPT_pruned_structured_2...,1.5020,10.4548,0.6998,0.4370,0.3395
3,llama_1B_INST_FT_sparseGPT_pruned_structured_5...,0.6342,1.1432,0.6347,0.3711,0.2009
4,llama_1B_INST_FT_sparseGPT_pruned_unstructured...,0.0094,0.3655,0.5980,0.2748,0.1336
5,llama_1B_INST_FT_sparseGPT_pruned_structured_2...,1.8947,12.4390,0.7160,0.4707,0.3855
6,llama_1B_INST_FT_sparseGPT_pruned_unstructured...,0.5466,3.9668,0.6554,0.3886,0.2245
7,llama_1B_INST_FT_sparseGPT_pruned_structured_7...,0.0029,0.1954,0.5377,0.2322,0.0983

In [93]:
import matplotlib.pyplot as plt
import seaborn as sns